allowedhostnames:
  - "localhost"
  - "127.0.0.1"
command: "/bin/zsh"
args:
  - "-c"
  - "cd ~; exec zsh"
serveraddr: "localhost"
serverport: 11223
pathterm: "/term"
pathapi: "api/v1/"
termbuffersize: 1024
loglevel: debug
connectionerrorlimit: 10
keepalivepingtimeout: 50
