import { PodTableItemType } from "./PodTable"

export const mockPods: PodTableItemType[] = [
    {
        key: 'kube-system/api-service',
        name: 'api-service',
        namespace: 'kube-system',
        status: 'Running',
        image: 'api-service:latest',
        age: '100m',
        restarts: 0,
    },
    {
        key: 'kube-system/kube-proxy',
        name: 'kube-proxy',
        namespace: 'kube-system',
        status: 'Running',
        image: 'kube-proxy:latest',
        age: '3days',
        restarts: 0,
    },
    {
        key: 'kube-system/etcd',
        name: 'etcd',
        namespace: 'kube-system',
        status: 'Running',
        image: 'etcd:latest',
        age: '100m',
        restarts: 3,
    },
    {
        key: 'foo/bar',
        name: 'bar',
        namespace: 'foo',
        status: 'Pending',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar2',
        name: 'bar2',
        namespace: 'foo',
        status: 'Succeeded',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar3',
        name: 'bar3',
        namespace: 'foo',
        status: 'Failed',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar4',
        name: 'bar4',
        namespace: 'foo',
        status: 'Unknown',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar5',
        name: 'bar2',
        namespace: 'foo',
        status: 'Succeeded',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar6',
        name: 'bar3',
        namespace: 'foo',
        status: 'Failed',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar7',
        name: 'bar4',
        namespace: 'foo',
        status: 'Unknown',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar8',
        name: 'bar2',
        namespace: 'foo',
        status: 'Succeeded',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar9',
        name: 'bar3',
        namespace: 'foo',
        status: 'Failed',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
    {
        key: 'foo/bar10',
        name: 'bar4',
        namespace: 'foo',
        status: 'Unknown',
        image: 'api-service:latest',
        age: '100m',
        restarts: 5,
    },
]